#include <iostream>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
int main()
{
    long long int limit{4000001};
    long long int a{1}, b{1}, c{};
    long long int s{};
    while(c<limit)
    {
        c=a+b;
        s+=(c%2==0)?c:0;
        a=b;
        b=c;
    }
    std::cout<<s<<std::endl;// 4613732
    return 0;
}